export const categories = [
  { name: "Technology", interested: true },
  { name: "Science", interested: false },
  { name: "Health", interested: true },
  { name: "Education", interested: false },
  { name: "Travel", interested: false },
  { name: "Sports", interested: true },
  { name: "Finance", interested: false },
  { name: "Environment", interested: false },
  { name: "Art", interested: false },
  { name: "History", interested: false },
  { name: "Music", interested: true },
  { name: "Movies", interested: false },
  { name: "Books", interested: false },
  { name: "Fashion", interested: false },
  { name: "Food", interested: false },
  { name: "Photography", interested: false },
  { name: "Fitness", interested: false },
  { name: "Gaming", interested: false },
  { name: "Gardening", interested: false },
  { name: "Programming", interested: false },
  { name: "DIY", interested: false },
  { name: "Marketing", interested: false },
  { name: "Entrepreneurship", interested: false },
  { name: "Business", interested: false },
  { name: "Social Media", interested: false },
  { name: "Psychology", interested: false },
  { name: "Biology", interested: false },
  { name: "Physics", interested: false },
  { name: "Chemistry", interested: false },
  { name: "Mathematics", interested: false },
  { name: "Astronomy", interested: false },
  { name: "Geography", interested: false },
  { name: "Politics", interested: false },
  { name: "Philosophy", interested: false },
  { name: "Economics", interested: false },
  { name: "Culinary Arts", interested: false },
  { name: "Interior Design", interested: false },
  { name: "Architecture", interested: false },
  { name: "Astrology", interested: false },
  { name: "Writing", interested: false },
  { name: "Comedy", interested: false },
  { name: "Literature", interested: false },
  { name: "Crafts", interested: false },
  { name: "Pet Care", interested: false },
  { name: "Real Estate", interested: false },
  { name: "Cooking", interested: false },
  { name: "Language Learning", interested: false },
  { name: "Career Development", interested: false },
  { name: "Volunteer Work", interested: false },
  { name: "Meditation", interested: false },
  { name: "Mindfulness", interested: false },
  { name: "Self-Help", interested: false },
  { name: "Relationships", interested: false },
  { name: "Home Improvement", interested: false },
  { name: "Productivity", interested: false },
  { name: "Public Speaking", interested: false },
  { name: "Cybersecurity", interested: false },
  { name: "Blockchain", interested: false },
  { name: "Machine Learning", interested: false },
  { name: "Data Science", interested: false },
  { name: "Artificial Intelligence", interested: false },
  { name: "Cryptocurrency", interested: false },
  { name: "Robotics", interested: false },
  { name: "Quantum Computing", interested: false },
  { name: "Network Security", interested: false },
  { name: "Virtual Reality", interested: false },
  { name: "Augmented Reality", interested: false },
  { name: "Nanotechnology", interested: false },
  { name: "Renewable Energy", interested: false },
  { name: "Genetics", interested: false },
  { name: "Climate Change", interested: false },
  { name: "Wildlife Conservation", interested: false },
  { name: "Oceanography", interested: false },
  { name: "Meteorology", interested: false },
  { name: "Agriculture", interested: false },
  { name: "Forestry", interested: false },
  { name: "Fishing", interested: false },
  { name: "Aerospace", interested: false },
  { name: "Automotive", interested: false },
  { name: "Manufacturing", interested: false },
  { name: "Logistics", interested: false },
  { name: "Supply Chain", interested: false },
  { name: "Hospitality", interested: false },
  { name: "Customer Service", interested: false },
  { name: "Human Resources", interested: false },
  { name: "Legal Studies", interested: false },
  { name: "Counseling", interested: false },
  { name: "Veterinary Science", interested: false },
  { name: "Pharmacy", interested: false },
  { name: "Nursing", interested: false },
  { name: "Public Health", interested: false },
  { name: "Community Service", interested: false },
  { name: "Retail", interested: false },
  { name: "Graphic Design", interested: false },
  { name: "Film Production", interested: false },
  { name: "Animation", interested: false },
  { name: "Performing Arts", interested: false },
  { name: "Event Planning", interested: false },
  { name: "Public Relations", interested: false },
];
